name: Sentinel

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - '*'                      # matches every branch that doesn't contain a '/'
      - '*/*'                    # matches every branch containing a single '/'
      - '**'                     # matches every branch
    paths:
      - '**.tf'
      - '**.hcl'
      - '**.sentinel'

permissions:
  contents: write
  pull-requests: write

jobs:
  job:
    name: Sentinel Test
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Branch
        id: branch
        run: echo "branch=${GITHUB_HEAD_REF}" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.branch.outputs.branch }}

      - name: 'Sentinel Format'
        id: fmt 
        uses: ConseilsTI/GitHubAction-SentinelFormat@v1.0.1
        with:
          check: false
          delete_comment: false

      - name: Git Push
        if: ${{ steps.fmt.outputs.exitcode == 2 }}
        run: |
          echo "INFO     | Pushing file(s) to the repository."  
          {  
            git config user.name "GitHub Action"
            git config user.email "notifications@github.com"
            git add -A
            git commit -m "Automated Terraform Formatting"
            git push -u origin ${{ steps.branch.outputs.branch }}
          } ||
          {
            echo "ERROR    | Unable to push file(s) to the repository.""
          }

      # - name: 'Sentinel Test'
      #   uses: benyboy84/GitHubAction_sentinel@main
      #   with:
      #     version: latest
      #     command: test
      #     working_dir: "./policies/global"
      #     comment: true
